### ISSUE TITLE
CRC64 "Jones" variant with initial condition

### ISSUE THREAD

**Issue by skandragon** [postmodern/digest-crc#11]
I have the need for a CRC 64 "Jones" variant, which is basically the CRC64 you have now with a modified table.  Additionally, I need to be able to set the initial value of the CRC state prior to the first update call.

I have code that works for this (just the table changed after all) and have added a `set(value)` method which will set the crc state.  However, as none of the other CRC calculators allow this set, I'm not sure if I should keep it class specific or make a PR that adds it to all CRCs.

Another option would be to change `reset()` to be `reset(initial_value = @initial_value)`

Which would you prefer?

**Comment by postmodern** [comment]
Good question about setting the initial value. I think you could override `#initialize` to accept an optional `init_crc` value? As for naming, I'd prefer you name it `Digest::CRC64::Jones` in the `lib/digest/crc64/jones.rb` file.

**Comment by postmodern** [comment]
`Digest::CRC64Jones` was added in 0.5.0. However, you'll need to sub-class it to allow changing the `@init_crc` value.
