### ISSUE TITLE
CRC-16-QT is the same as CRC-16-X-25

### ISSUE THREAD

**Issue by dearblue** [postmodern/digest-crc#17]
CRC-16-QT defined by digest-crc has exactly the same characteristics as CRC-16-X-25.
I think it is better to redefine it as `Digest::CRC16QT = Digest::CRC16X25` as an alias, or to abolish `Digest::CRC16QT` itself.

**Comment by postmodern** [comment]
@dearblue are you 100% sure about that? `Digest::CRC16QT` inherits from `Digest::CRC16CCITT`, which has a slightly different `TABLE` than `Digest::CRC16X25`. Also for some reason `Digest::CRC16QT` defines an additional `FINAL_XOR` which is applied in `#checksum` in addition to the `XOR_MASK`/`@xor_mask`; not entirely sure why though.

**Comment by dearblue** [comment]
> are you 100% sure about that?

Yes. I am 100% sure.

### Characteristics of both confirmed from "digest-crc" implementation

|                       | `Digest::CRC16X25` | `Digest::CRC16QT` |
| :-------------------: | :----------------: | :---------------: |
| Word size             | 16 bits            | 16 bits           |
| Generator polynomial  | `0x1021`           | `0x1021`          |
| Initial value         | `0xffff`           | `0xffff`          |
| Bit reflected input   | Yes                | Yes               |
| Bit reflected output  | Yes                | Yes               |
| Output xor mask       | `0xffff`           | `0xffff`          |

### Word size

Both are 16-bit.

```irb
% irb27 -r digest/crc16_x_25 -r digest/crc16_qt
irb(main):001:0> Digest::CRC16X25::WIDTH
=> 16
irb(main):002:0> Digest::CRC16QT::WIDTH
=> 16
```

### Generator polynomial

Both are `0x1021`.

`Digest::CRC16X25#update` (actually `Digest::CRC16#update`) uses a lookup table with reversed bit ordering.
Therefore, the value obtained by reversing the bit order of `table[128]` is the generator polynomial.

`Digest::CRC16QT#update` uses a lookup table with normal bit ordering.
Therefore, the value of `table[1]` becomes the generator polynomial as it is.

```irb
% irb27 -r digest/crc16_x_25 -r digest/crc16_qt
irb(main):001:0> def bitreflect16(n); 16.times.reduce(0) { |a, *| a = (a << 1) | n[0]; n >>= 1; a }; end
=> :bitreflect16
irb(main):002:0> bitreflect16(Digest::CRC16X25::TABLE[128]).to_s(16)
=> "1021"
irb(main):003:0> Digest::CRC16QT::TABLE[1].to_s(16)
=> "1021"
```

### Initial value

Both are `0xffff`.

```irb
% irb27 -r digest/crc16_x_25 -r digest/crc16_qt
irb(main):001:0> Digest::CRC16X25::INIT_CRC.to_s(16)
=> "ffff"
irb(main):002:0> Digest::CRC16QT::INIT_CRC.to_s(16)
=> "ffff"
```

### Bit reflected input

Both are "Yes".

`Digest::CRC16X25#update` (`Digest::CRC16#update`) uses a lookup table with reversed bit ordering.
Since it uses the input as it is, it is "Bit reflected input".

`Digest::CRC16QT#update` uses a lookup table with normal bit ordering.
However, it is a "Bit reflected input" because it inverts the input bits before processing.

### Bit reflected output

Both are "Yes".

The `@crc` of `Digest::CRC16X25` is already reversed bit ordering and is output as it is.

The `@crc` of `Digest::CRC16QT#update` is normal bit ordering, but the bit order is reversed before output.

### Output xor mask

Both are `0xffff`.

`Digest::CRC16QT::XOR_MASK` is `0`, but it uses its own `Digest::CRC16QT::FINAL_XOR` to xor.

```irb
% irb27 -r digest/crc16_x_25 -r digest/crc16_qt
irb(main):001:0> Digest::CRC16X25::XOR_MASK.to_s(16)
=> "ffff"
irb(main):002:0> Digest::CRC16QT::XOR_MASK.to_s(16)
=> "0"
irb(main):003:0> Digest::CRC16QT::FINAL_XOR.to_s(16)
=> "ffff"
```

### If you still feel uneasy...

I think you will have to actually compare the two.

```ruby
# check-x25-qt.rb
require "digest/crc16_x_25"
require "digest/crc16_qt"
require "securerandom"

100000000.times do |i|
  print "\r#{i}  " if i % 1000 == 0
  src = SecureRandom.bytes(SecureRandom.random(1024))
  a = Digest::CRC16X25.hexdigest(src)
  b = Digest::CRC16QT.hexdigest(src)
  p [a, b, src] unless a == b
end

puts
```

**Comment by postmodern** [comment]
Aliased it ad updated the specs in 0933a9d1b58f10167c8deaee39a868d7e00b48f0. Will merge and release 0.6.0 tomorrow.
