### ISSUE TITLE
Require gem `rake` but no dependency

### ISSUE THREAD

**Issue by Whirlwind** [postmodern/digest-crc#18]
```
$ bundle install
....
    Installing digest-crc 0.6.0 (was 0.5.1) with native extensions
    Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
    
    current directory:
    /Users/guoqi/.bundle/vendor/ruby/2.5.0/gems/digest-crc-0.6.0/ext/digest
    rake
    RUBYARCHDIR=/Users/guoqi/.bundle/vendor/ruby/2.5.0/extensions/x86_64-darwin-18/2.5.0/digest-crc-0.6.0
    RUBYLIBDIR=/Users/guoqi/.bundle/vendor/ruby/2.5.0/extensions/x86_64-darwin-18/2.5.0/digest-crc-0.6.0
    /Users/guoqi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:289:in
    `find_spec_for_exe': can't find gem rake (>= 0.a) with executable rake
    (Gem::GemNotFoundException)
    from
    /Users/guoqi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:308:in
    `activate_bin_path'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0@global/bin/rake:23:in `<main>'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `eval'
    	from /Users/guoqi/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:24:in `<main>'
```
There is not `rake` gem in my mac and my project. I think that should add a dependency in gemspec?

**Comment by asmenter15** [comment]
I am having this exact same issue. digest-crc is a dependency of Fastlane, which is causing fastlane gem install to fail. My current hack around this problem is forcing an earlier version of digest-crc before installing fastlane gem.

**Comment by dmarjanovic** [comment]
The same as @asmenter15 commented above. Fixing `0.5.1` in Gemfile with latest stable Fastlane version (atm `2.149.1`) worked for us for building iOS app.

**Comment by kishikawakatsumi** [comment]
Another workaround is adding `rake` dependency explicitly, like the following. 

```
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane"
gem "versionomy"
gem "rake" # <= Add this line
```

**Comment by donghoang89** [comment]
I am running into the same issue.

Previously, I was able to install digest-crc-0.5.1 without trouble
'''
Fetching: digest-crc-0.5.1.gem (100%)
Successfully installed digest-crc-0.5.1
'''

However, I started running into missing rake issue after upgrading to digest-crc-0.6.0
'''
Fetching: digest-crc-0.6.0.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing calculi_terra.gem:
	ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/2.5.0/gems/digest-crc-0.6.0/ext/digest
rake RUBYARCHDIR=/usr/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/digest-crc-0.6.0 RUBYLIBDIR=/usr/lib/ruby/gems/2.5.0/extensions/x86_64-linux/2.5.0/digest-crc-0.6.0
sh: rake: not found

rake failed, exit code 127
'''

**Comment by postmodern** [comment]
`rake` is now a full dependency as of 9efa59da2917c8d916a60a6680d420c172cfa4ed.

**Comment by maxTeste** [comment]
hey guys
can someone help me?
I'm trying to run fastlane with pipeline azure and then with fastlane call discord_notifier (https://github.com/nikolas-theodosis/fastlane-discord_notifier)
so
pipeline azure -> fastlane -> discord_notifier

if I only test fastlane with the discord notifier it works fine, but if the pipline triggers the fastlane (bundle exec fastlane dev) it doesn't work

![image](https://user-images.githubusercontent.com/75133022/131880383-0ce08bd4-c73a-433c-bc60-00cda8366a68.png)

![image](https://user-images.githubusercontent.com/75133022/131880717-96d4b1bb-cc25-4f6b-bf99-061e4ae308f7.png)


![image](https://user-images.githubusercontent.com/75133022/131880458-77d92eb5-17b5-4d14-a340-1b4ef2109aa0.png)


![image](https://user-images.githubusercontent.com/75133022/131880275-ef8df074-7c99-4e23-873c-dafcf2e67735.png)


![image](https://user-images.githubusercontent.com/75133022/131880310-d250bff5-1ae7-4fdd-9327-ea7f2a0de98d.png)

![image](https://user-images.githubusercontent.com/75133022/131880341-d82f6ed0-1984-4924-bfec-831f6e984e32.png)

**Comment by postmodern** [comment]
@maxTeste that doesn't look like it's related to the above issue. Could you post the output of `bundle install` where it installs/compiles `digest-crc`?

**Comment by maxTeste** [comment]
#32
