### ISSUE TITLE
Can't install without Xcode command line tools

### ISSUE THREAD

**Issue by jviotti** [postmodern/digest-crc#21]
The README states that:

> (`digest-crc`) supports optional C extensions which increases performance by ~40x. If the C extensions cannot be compiled for whatever reason, `digest-crc` will automatically fallback to the pure-Ruby implementation.

However, the gem's native extensions can't be installed (on Catalina at least) without Xcode command line tools and no fallback seems to be provided:

![Screen Sharing Picture 26 August 2020 at 01 42 41 BST](https://user-images.githubusercontent.com/2192773/91241845-be4d9c00-e73d-11ea-8710-1a1cae1b4b71.png)

**Comment by postmodern** [comment]
e68b53cc826bc779391726f0e97815f3ff6ca879 might fix this.

**Comment by postmodern** [comment]
Should be fixed in 0.6.2. Added a note to the [README](https://github.com/postmodern/digest-crc#install) and added [Integration Testing](https://github.com/postmodern/digest-crc/tree/master/spec/integration) where we install a freshly built `digest-crc.gem` into a variety of docker images.
