### ISSUE TITLE
Could not find gem 'digest-crc (~> 0.6.1)' in locally installed gems

### ISSUE THREAD

**Issue by maxTeste** [postmodern/digest-crc#32]
hey guys
can someone help me?
I'm trying to run fastlane with pipeline azure and then with fastlane call discord_notifier (https://github.com/nikolas-theodosis/fastlane-discord_notifier)
so
pipeline azure -> fastlane -> discord_notifier

if I only test fastlane with the discord notifier it works fine, but if the pipline triggers the fastlane (bundle exec fastlane dev) it doesn't work

erro on pipeline ->  bundle exec fastlane dev: 
![image](https://user-images.githubusercontent.com/75133022/131880383-0ce08bd4-c73a-433c-bc60-00cda8366a68.png)

![image](https://user-images.githubusercontent.com/75133022/131880717-96d4b1bb-cc25-4f6b-bf99-061e4ae308f7.png)

yaml file pipeline:
![image](https://user-images.githubusercontent.com/75133022/131880458-77d92eb5-17b5-4d14-a340-1b4ef2109aa0.png)

running only fastlane and notifier:
![image](https://user-images.githubusercontent.com/75133022/131880275-ef8df074-7c99-4e23-873c-dafcf2e67735.png)

![image](https://user-images.githubusercontent.com/75133022/131880310-d250bff5-1ae7-4fdd-9327-ea7f2a0de98d.png)

![image](https://user-images.githubusercontent.com/75133022/131880341-d82f6ed0-1984-4924-bfec-831f6e984e32.png)

digest-crc is instaled locally

**Comment by postmodern** [comment]
@maxTeste Could you post the output of `bundle install` where it installs/compiles `digest-crc`?

**Comment by maxTeste** [comment]
![image](https://user-images.githubusercontent.com/75133022/131965792-52126d57-74ac-4549-9af9-6d98cd68d71a.png)

**Comment by maxTeste** [comment]
![image](https://user-images.githubusercontent.com/75133022/131969830-341a18c4-a0b1-4e7f-94cc-9e6ac3499913.png)

**Comment by maxTeste** [comment]
![image](https://user-images.githubusercontent.com/75133022/131985617-a31dba78-9c81-49c4-9665-66ca686a26b1.png)

**Comment by maxTeste** [comment]
hey @postmodern when i run the bundle exec fastlane dev
![image](https://user-images.githubusercontent.com/75133022/132020576-7cd556a9-41be-49c6-bcb2-d6ef7ba7a03e.png)

and i already have rbnacl-libsodium installed.... 
it give me this error ... 
can u help me with this? pls 

![image](https://user-images.githubusercontent.com/75133022/132020501-c666435f-ec4e-4aa6-bf25-788a6410bda8.png)

**Comment by postmodern** [comment]
Looks like `digest-crc` is installed. Not sure how you got the original error, as I'm not familiar with fastlane. Also I'm not sure about the other `FastLane::UpdateChecker` error. The `libsodium` error is probably because you need to install `libsodium` from the system's package manager (`sudo apt-get install libsodium-dev`).

Are you still getting the `digest-crc` gem error?

**Comment by maxTeste** [comment]
@postmodern no. now the only error i get is the sodium error.. that can't find it . but i have installed it
i can't really use sudo apt-get install libsodium-dev because is azure pipeline and i need to use yaml file. every time i run pipeline it creates a new VM to run it ...

**Comment by postmodern** [comment]
@maxTeste ok sounds like the problem isn't with digest-crc anymore. As for installing `libsodium` (which is a C library that `rbnacl` loads) you'll need to check the Azure Pipeline docs or search Google. I did a quick google search and found this StackOverflow answer: https://stackoverflow.com/questions/56285503/install-program-on-azure-pipelines
